package ch.sbb.matsim.umlego.timetable;

import ch.sbb.matsim.umlego.config.hadoop.FileSystemUtil;
import ch.sbb.matsim.umlego.util.PathUtil;
import ch.sbb.matsim.umlego.util.RunId;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.time.LocalDate;

import static ch.sbb.matsim.umlego.config.hadoop.FileSystemUtil.getRootDir;

/**
 * The MATSimTimetableBackuper copies files generated by Hafas2UmlegoSchedule converter
 * from local file system to Azure Blob Storage.
 * Size of all backed up files is approx. 2.5 MB / day
 * Time spent for running the backup is approx. 10 sec. (OpenShift DEVX environment)
 */
public class MATSimTimetableBackuper {

    private static final Logger LOG = LogManager.getLogger(MATSimTimetableBackuper.class);

    /**
     * Factory method returning instance.-
     *
     * @return MATSimTimetableBackuper
     */
    public static MATSimTimetableBackuper create() {
        return new MATSimTimetableBackuper();
    }

    /**
     * Backups local schedule folder (incl. all subdirectories and files).
     *
     * @param localScheduleFolder source folder in local file system
     * @param runId run-id as entered (or generated) by Argo Workflow.
     * @param targetDate the Umlego date.
     */
    public void backup(String localScheduleFolder, RunId runId, int year, LocalDate targetDate) {
        try {
            LOG.info("Backing up converted MATSim timetable files to Azure Blob Storage");
            FileSystem fs = FileSystemUtil.getFileSystem();

            Path srcPath = new Path(localScheduleFolder);
            LOG.info(" src: " + srcPath);

            Path dstPath = new Path(getRootDir() + PathUtil.getRemoteOutputFolder(runId, year, targetDate));
            LOG.info(" dst: " + dstPath);

            fs.copyFromLocalFile(srcPath, dstPath);
            LOG.info("Backup completed");
        } catch (IOException e) {
            LOG.warn("Backing up MATSim timetable files failed.", e);
        }
    }
}
